#!/usr/bin/env bash

# Default values
CARD="${args[0]}"
MIXER="${args[1]}"
SCONTROL="${args[2]}"

if [[ -z "$CARD" ]]; then
    CARD=0
fi

if [[ -z "$MIXER" ]]; then
    MIXER=pulse
fi

if [[ -z "$SCONTROL" ]]; then
    SCONTROL=Master
fi

if [[ "$MIXER" == "alsa" ]]; then
    case $BLOCK_BUTTON in
        3) amixer -c "$CARD" -q sset $SCONTROL toggle ;; # right click, mute/unmute
        4) amixer -c "$CARD" -q sset $SCONTROL 5%+ ;;    # scroll up, increase
        5) amixer -c "$CARD" -q sset $SCONTROL 5%- ;;    # scroll down, decrease
    esac
else
    case $BLOCK_BUTTON in
        3) amixer -c "$CARD" -q -D pulse sset $SCONTROL toggle ;; # right click, mute/unmute
        4) amixer -c "$CARD" -q -D pulse sset $SCONTROL 5%+ ;;    # scroll up, increase
        5) amixer -c "$CARD" -q -D pulse sset $SCONTROL 5%- ;;    # scroll down, decrease
    esac
fi

states=$(amixer -c $CARD -M -D $MIXER get $SCONTROL | sed -rn 's/^.*\[(.*)\]$/\1/p')

#amixer -c $CARD -M -D $MIXER get $SCONTROL | grep -o -E "[[:digit:]]+%"
vol=$(amixer -c $CARD -M -D $MIXER get $SCONTROL | sed -rn 's/.*\[([[:digit:]]+%)\].*/\1/p' | uniq)
for state in $states; do
    if [ "$state" = "on" ]; then
        printf '%s' "$vol" | uniq
    else
        printf '%s' "<span foreground=\"#F00\">$vol</span>" | uniq
    fi
done
